# Generated by Django 4.2.1 on 2023-05-30 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syncsocial', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_dates', to=settings.AUTH_USER_MODEL),
        ),
    ]
